language: python

jobs:
  include:
    - name: 'Retail'
      before_install:
        - export GAME_VERSION="retail"
        - git clone https://github.com/Gethe/wow-ui-source tests/wow-ui-source

    - name: 'Classic'
      before_install:
        - export GAME_VERSION="classic"
        - git clone https://github.com/Gethe/wow-ui-source tests/wow-ui-source -b classic_era

    - name: 'TBC'
      before_install:
        - export GAME_VERSION="bcc"
        - git clone https://github.com/Gethe/wow-ui-source tests/wow-ui-source -b classic

addons:
  apt:
    packages:
      - luarocks

cache: pip

install:
  - sudo luarocks install luacheck
  - sudo luarocks install luaunit
  - sudo luarocks install luacov
  - git clone https://github.com/Beast-Masters-addons/build_utils tests/build_utils
  - pip install -r tests/build_utils/utils/requirements.txt
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -d -z -g $GAME_VERSION
  - mv .release/Broker_WhereAmI/libs .
  - python tests/build_utils/utils/BuildMapData.py

script:
  - luacheck addon --no-color -q
  - cd tests
  - for test in test*.lua; do lua -lluacov "$test"; done

after_script:
  - bash <(curl -s https://codecov.io/bash)

after_success:
  - cd $TRAVIS_BUILD_DIR
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g $GAME_VERSION