name: Test and package

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    tags:
      - '**'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game_version: [ 'classic', 'cata', 'retail' ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          path: 'addon'
          annotate: warning

      - name: Install lua dependencies
        run: |
          sudo luarocks install luaunit
          sudo luarocks install luacov

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install zip subversion

      - name: Build YAML and move toc
        run: |
          python files/yaml_merge.py
          git add -f Broker_WhereAmI.toc
        env:
          GAME_VERSION: ${{ matrix.game_version }}

      - name: Build the addon
        uses: BigWigsMods/packager@v2.3.1
        with:
          args: -z -d -g ${{ matrix.game_version }}

      - name: Move libraries and toc
        run: | 
          mv .release/Broker_WhereAmI/libs .
          mv .release/Broker_WhereAmI/Broker_WhereAmI.toc .
          mv .release/Broker_WhereAmI/embeds.xml .

      - name: Strip invalid characters from LibTouristClassic-1.0.lua
        if: matrix.game_version == 'cata'
        run: sed -i '1s/^\xEF\xBB\xBF//' libs/LibTouristClassic/LibTouristClassic-1.0.lua

      - name: Patch typo in LibTouristClassic-1.0.lua
        if: matrix.game_version == 'cata'
        run: git apply ../../files/tourist.patch
        working-directory: libs/LibTouristClassic

      - name: Strip invalid characters from LibTouristClassicEra.lua
        if: matrix.game_version == 'classic'
        run: sed -i '1s/^\xEF\xBB\xBF//' libs/LibTouristClassicEra/LibTouristClassicEra.lua

      - name: Resolve toc
        run: python tests/build_utils/utils/parse_toc.py Broker_WhereAmI.toc

      - name: Download classic UI source
        if: matrix.game_version == 'classic'
        uses: actions/checkout@v4
        with:
          repository: Gethe/wow-ui-source
          path: tests/wow-ui-source
          ref: 'classic_era'

      - name: Download WotLK UI source
        if: matrix.game_version == 'cata'
        uses: actions/checkout@v4
        with:
          repository: Gethe/wow-ui-source
          path: tests/wow-ui-source
          ref: 'classic'

      - name: Download retail UI source
        if: matrix.game_version == 'retail'
        uses: actions/checkout@v4
        with:
          repository: Gethe/wow-ui-source
          path: tests/wow-ui-source

      - name: Run tests
        run: for test in test*.lua; do lua -lluacov "$test"; done
        working-directory: tests
        env:
          GAME_VERSION: ${{ matrix.game_version }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game_version: [ 'classic', 'cata', 'retail' ]

    needs:
      - test

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build YAML and move toc
        run: |
          python files/yaml_merge.py
          git add -f Broker_WhereAmI.toc
          git rm -rf tests
          git rm -rf files
        env:
          GAME_VERSION: ${{ matrix.game_version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install zip subversion

      - name: WoW Packager
        uses: BigWigsMods/packager@v2.3.1
        with:
          args: -o -g ${{ matrix.game_version }}

      - uses: actions/upload-artifact@v4
        with:
          name: Broker_WhereAmI-${{ matrix.game_version }}
          path: .release
