name: Test and package

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, build_test ]
    tags:
      - '**'
  pull_request:
    branches: [ master, build_test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game_version: [ 'classic', 'bcc', 'retail' ]

    steps:
      - uses: actions/checkout@v1

      - name: Get build utils
        uses: actions/checkout@v2
        with:
          repository: Beast-Masters-addons/build_utils
          path: tests/build_utils

      - name: Build map data
        run: python tests/build_utils/utils/BuildMapData.py

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          path: 'addon'
          annotate: warning

      - name: Install lua dependencies
        run: |
          sudo luarocks install luaunit
          sudo luarocks install luacov

      - name: Move toc and add LibTourist to .pkgmeta
        run: |
          cat files/${{ matrix.game_version }}/externals.yml >> .pkgmeta.yml
          mv files/${{ matrix.game_version }}/Broker_WhereAmI.toc Broker_WhereAmI.toc
          rm -R files

      - name: Build the addon
        uses: BigWigsMods/packager@v2.0.3
        with:
          args: -z -d

      - name: Move libraries
        run: mv .release/Broker_WhereAmI/libs .

      - name: Strip invalid characters from LibTouristClassic-1.0.lua
        if: matrix.game_version == 'bcc'
        run: sed -i '1s/^\xEF\xBB\xBF//' libs/LibTouristClassic/LibTouristClassic-1.0.lua

      - name: Strip invalid characters from LibTouristClassicEra.lua
        if: matrix.game_version == 'classic'
        run: sed -i '1s/^\xEF\xBB\xBF//' libs/LibTouristClassicEra/LibTouristClassicEra.lua

      - name: Resolve toc
        run: python tests/build_utils/utils/parse_toc.py Broker_WhereAmI.toc

      - name: Download classic UI source
        if: matrix.game_version == 'classic'
        uses: actions/checkout@v2
        with:
          repository: Gethe/wow-ui-source
          path: tests/wow-ui-source
          ref: 'classic_era'

      - name: Download Burning Crusade Classic UI source
        if: matrix.game_version == 'bcc'
        uses: actions/checkout@v2
        with:
          repository: Gethe/wow-ui-source
          path: tests/wow-ui-source
          ref: 'classic'

      - name: Download retail UI source
        if: matrix.game_version == 'retail'
        uses: actions/checkout@v2
        with:
          repository: Gethe/wow-ui-source
          path: tests/wow-ui-source

      - name: Run tests
        run: for test in test*.lua; do lua -lluacov "$test"; done
        working-directory: tests
        env:
          GAME_VERSION: ${{ matrix.game_version }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game_version: [ 'classic', 'bcc', 'retail' ]

    needs:
      - test

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1

      - name: Get build utils
        uses: actions/checkout@v3
        with:
          repository: Beast-Masters-addons/build_utils
          path: tests/build_utils

      - name: Build map data
        run: python tests/build_utils/utils/BuildMapData.py

      - name: Move toc and add LibTourist to .pkgmeta
        run: |
          cat files/${{ matrix.game_version }}/externals.yml >> .pkgmeta.yml
          mv files/${{ matrix.game_version }}/Broker_WhereAmI.toc Broker_WhereAmI.toc
          rm -R files

      - name: WoW Packager
        uses: BigWigsMods/packager@v2.0.3
        with:
          args: -o

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.game_version }}
          path: .release
